# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: code.liquid_think
description: "Here, I post on basically...just programming. Python, C, C++, Java, hell even Assembly. Anything that i'm really doing, or am planning to do, is going on this site"
author: Andrew Plaza
github: https://github.com/InsidiousMind
about: Student

baseurl: ""
url: "http://code.liquidthink.net/"

# disqus_shortname: aboutashu
# google_analytics: UA-72862926-1

#share:
# twitter_username: @liquid_think
# fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown

assets:
  compress:
    css: sass
    js: uglifier

  autowrite: true
  cache: .asset-cache
  cache_type: filesystem
  cdn: code-liquidthink.netlify.com
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true

  assets:
    - "*.png"
    - "bundle.css"

  sources:
    - _assets/css
    - _assets/fonts
    - _assets/img
    - _assets/js
    - _assets/projects

  features:
    liquid: false
    integrity: true
    automatic_img_size: true
    automatic_img_alt : true

exclude: [.asset-cache]

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-assets
