# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
react:
  title: Code.Liquid_Think
  name: Andrew Plaza
  menu_right_subtitle: Blogger || Computer Scientist
  avatar: http://www.gravatar.com/avatar/1018d9cd283965fc227390accb707132
  logo: static/img/logo.png
  email: aplaza@liquidthink.net
  description: > # this means to ignore newlines until "baseurl:"
    Welcome to Code.Liquid_Think. I post here on anything to do with programming and my current projects/thoughts on the programo-sphere
  baseurl: "" # the subpath of your site, e.g. /blog
  url: "http://code.liquidthink.net" # the base hostname & protocol for your site
  permalink: /posts/:title
  social:
    twitter: http://twitter.com/liquid_think
    github: http://github.com/InsidiousMind
    facebook: http://facebook.com/liquidthinknet
    code: http://livecoding.tv/insidious #livecoding.tv handle
    google-plus: http://plus.google.com/+LiquidthinkNet #make sure to include the '+'
    rss: feed.xml



title: Code.Liquid_Think
name: Andrew Plaza
menu_right_subtitle: Blogger || Computer Scientist
avatar: http://api.adorable.io/avatar/aplaza@liquidthink.net
logo: static/img/logo.png
email: aplaza@liquidthink.net
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Code.Liquid_Think. I post here on anything to do with programming and my current projects/thoughts on the programo-sphere
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://code.liquidthink.net" # the base hostname & protocol for your site
permalink: /posts/:title


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      type: "post"
# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

source: src
destination: public

assets:
  compress:
    css: sass
    js: false

  autowrite: true
  cache: .asset-cache
  cache_type: filesystem
  cdn: www.example.com
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true

  assets:
    - "*.png"
    - "bundle.css"
    - "bundle.js.map"
    - "*.svg"
    - "*.eof"
    - "*.ttf"

  sources:
    - src/_assets/css
    - src/_assets/fonts
    - src/_assets/img
    - src/_assets/projects

  features:
    liquid: false
    integrity: true
    automatic_img_size: true
    automatic_img_alt : true

exclude: ['node_modules', 'Gemfile', '.asset-cache', 'build-prod.sh', 'build-dev.sh', 'src/_drafts']

gems:
  - jekyll-assets
  - jekyll_pages_api
  - jekyll-react
